### ISSUE TITLE
Contao 4.5: Wizard funktioniert nicht

### ISSUE THREAD

**Issue by wiphi** [netzmacht/contao-icon-wizard#11]
Umgebung: 
`Contao 4.5.3 / Ubuntu 17.10 / PHP 7.1 / Browser: Firefox 58, Vivaldi 1.13`

Ich bin gerade dabei das [netzmacht/contao-font-awesome](https://github.com/netzmacht/contao-font-awesome) zu testen und ggf. in eine Erweiterung zu integrieren. 

Beim Öffnen des Wizards für die Icon-Auswahl zeigt er nur die Namen der Icons:
![bildschirmfoto von 2018-02-03 18-56-24](https://user-images.githubusercontent.com/25878910/35770033-9d0fa4de-0914-11e8-80aa-889aac21b29b.png)

ich habe in der Console nachgeschaut und gesehen, dass dort falsche Links geladen werden. 
Anbei die Consolen-Ausgabe:
`GET http://winkelweb.local/system/modules/icon-wizard/public/system/modules/icon-wizard/assets/popup.css 404 (Not Found)
popup.php:7 GET http://winkelweb.local/system/modules/icon-wizard/public/assets/css/basic.css+main.css-b9a2588d.css net::ERR_ABORTED
popup.php:10 GET http://winkelweb.local/system/modules/icon-wizard/public/assets/css/faq.min.css+news.min.css+backend.css+calendar.min.css+font-aweso...-8e0cbefe.css net::ERR_ABORTED
popup.php:10 GET http://winkelweb.local/system/modules/icon-wizard/public/system/modules/icon-wizard/assets/wizard.css 404 (Not Found)
popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:10 GET http://winkelweb.local/system/modules/icon-wizard/public/bundles/markocupiccalendareventbooking/css/be_stylesheet.css net::ERR_ABORTED
popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:14 GET http://winkelweb.local/system/modules/icon-wizard/public/system/modules/icon-wizard/assets/iconWizard.js net::ERR_ABORTED
popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:11 GET http://winkelweb.local/system/modules/icon-wizard/public/assets/js/mootools.min.js+mootao.min.js+core.min.js+hover.js-496e82e3.js net::ERR_ABORTED
popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:12 Uncaught ReferenceError: Locale is not defined
    at popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:12
(anonymous) @ popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:12
popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:14 GET http://winkelweb.local/system/modules/icon-wizard/public/system/modules/icon-wizard/assets/iconWizard.js net::ERR_ABORTED
popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:3779 Uncaught TypeError: window.addEvent is not a function
    at popup.php?table=tl_content&field=fontAwesome_icon&name=ctrl_fontAwesome_icon&id=20:3779`

Im Inspektor konnte ich das Problem damit lösen, dass ich vor alle Links noch ein `/` gesetzt habe.

**Comment by dmolineus** [comment]
Hier wurde entweder etwas in Contao 4.5 geändert, oder irgendwas stimmt in der lokalen Installation nicht. Unter 4.4 habe ich die Erweiterung problemlos im Einsatz.

Ein `/` am Anfang bereitet dann vermutlich Probleme im Debug Modus mit `app_dev.php/` in der Url.

**Comment by wiphi** [comment]
Du hast Recht, der base-Tag ist Mist. Um sicher zu gehen, installiere ich mir eben ein frisches Contao 4.5 und melde mich wieder.

**Comment by wiphi** [comment]
So Contao 4.5 in eine neu Instanz installiert, Problem besteht weiterhin. Komischerweise liefert 
`$this->Environment->base` als Pfad
`http://contao45.local/system/modules/icon-wizard/public/` zurück. Ich teste jetzt noch eine 4.4 auf meinem System.

**Comment by wiphi** [comment]
In Contao 4.4 liefert er den richtigen base-Tag. Scheinbar gab es da eine Änderung in der 4.5...
Zusammenfassung: 
Contao 4.4 funktioniert
Contao 4.5 funktioniert nicht

**Comment by dmolineus** [comment]
Danke @wiphi für die bisherigen Tests und der Bestätigung meiner Vermutung. Kannst du schauen, ob https://github.com/netzmacht/contao-icon-wizard/pull/12 das Problem behebt? Habe erst nächste Woche wieder eine Contao 4.5 Testumgebung zur Verfügung.

**Comment by wiphi** [comment]
#12 funktioniert ;) Kleine Ursache, große Wirkung!

**Comment by dmolineus** [comment]
Release https://github.com/netzmacht/contao-icon-wizard/releases/tag/1.2.3 beinhaltet nun den Patch.
