### ISSUE TITLE
 Invalid call. Field does not exists or is not an icon wizard thrown

### ISSUE THREAD

**Issue by kzorluoglu** [netzmacht/contao-icon-wizard#7]
DCA sieht so aus,
![Image of Yaktocat](http://i.hizliresim.com/W10MnQ.png)

aber bekomme ich diese Fehlermeldung?
![Image of Yaktocat](http://i.hizliresim.com/a2LO5g.png)

Fatal error: Uncaught exception RuntimeException with message Invalid call. Field does not exists or is not an icon wizard thrown in composer/vendor/netzmacht/contao-iconwizard/src/WizardController.php on line 129
#0 composer/vendor/netzmacht/contao-iconwizard/src/WizardController.php(58): Netzmacht\Contao\IconWizard\WizardController->initializeDataContainer('tl_content', '')
#1 system/modules/icon-wizard/public/popup.php(21): Netzmacht\Contao\IconWizard\WizardController->run()
#2 {main}

Danke.

**Comment by dmolineus** [comment]
Entspricht dies einem direkten Feld oder wird hier etwas wie Custom Elements oder der Multi Column Wizards eingesetzt? Beides kann durchaus zu Problemen führen.

**Comment by dmolineus** [comment]
Geschlossen wegen fehlenden Feedback. Tritt der Fehler noch auf, bitte hier nochmal berichten.
