### ISSUE TITLE
Popup-Url - strTable anstelle \Input::get('table')

### ISSUE THREAD

**Issue by tognit** [netzmacht/contao-icon-wizard#9]
Wenn man den iconWizard für die Seiten (Seitenstruktur) verwenden möchte, kommt in der Icon-Auswahl eine Fehlermeldung. Es fehlt ein Get-Parameter für (table=tl_page), doch bei der Bearbeiten der Seiten ist in der URL kein "table" vorhanden.

Daher gibt die Ausgabe über "\Input::get('table')" keinen Wert aus. Wenn man anstelle "\Input::get('table')" mit "$this->strTable" den Wert sucht, funktioniert es bei mir tiptop.

IconWizard.php

Anstelle:

```
public function generate()
    {
        $url = sprintf(
            'system/modules/icon-wizard/public/popup.php?table=%s&amp;field=%s&amp;name=ctrl_%s&amp;id=%s',
            \Input::get('table'),
            $this->strField,
            $this->name,
            \Input::get('id')
        );
```

wäre so besser??

```
public function generate()
    {
        $url = sprintf(
            'system/modules/icon-wizard/public/popup.php?table=%s&amp;field=%s&amp;name=ctrl_%s&amp;id=%s',
            $this->strTable,
            $this->strField,
            $this->name,
            \Input::get('id')
        );
```

**Comment by dmolineus** [comment]
Ich habe die Änderungen so übernommen. Könntest du bitte den develop Branch so testen und Bescheid geben, ob alles funktioniert?
